### ISSUE TITLE
Integration tests failing

### ISSUE THREAD

**Issue by s-KaiNet** [s-KaiNet/spsave#18]
Some integration tests failing after recent updates in SharePoint Online.

**Comment by s-KaiNet** [comment]
When trying to save file for SP Online with `checkin=true` you will probably receive: 

```
Unhandled rejection TypeError: err.error.indexOf is not a function
    at C:\Projects\spsave\lib\src\core\FileSaver.js:99:74
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at FileSaver.saveFile (C:\Projects\spsave\lib\src\core\FileSaver.js:94:19)

    at FileSaver.save (C:\Projects\spsave\lib\src\core\FileSaver.js:37:18)
    at saveSingleFile (C:\Projects\spsave\lib\src\core\SPSave.js:69:47)
    at C:\Projects\spsave\lib\src\core\SPSave.js:36:13
From previous event:
    at Object.spsave (C:\Projects\spsave\lib\src\core\SPSave.js:12:12)
    at Context.<anonymous> (C:\Projects\spsave\lib\test\integration\integration.spec.js:274:22)
    at callFnAsync (C:\Projects\spsave\node_modules\gulp-mocha\node_modules\mocha\lib\runnable.js:349:8)
    at Test.Runnable.run (C:\Projects\spsave\node_modules\gulp-mocha\node_modules\mocha\lib\runnable.js:301:7)
    at Runner.runTest (C:\Projects\spsave\node_modules\gulp-mocha\node_modules\mocha\lib\runner.js:422:10)
    at C:\Projects\spsave\node_modules\gulp-mocha\node_modules\mocha\lib\runner.js:528:12
    at next (C:\Projects\spsave\node_modules\gulp-mocha\node_modules\mocha\lib\runner.js:342:14)
    at C:\Projects\spsave\node_modules\gulp-mocha\node_modules\mocha\lib\runner.js:352:7
    at next (C:\Projects\spsave\node_modules\gulp-mocha\node_modules\mocha\lib\runner.js:284:14)
    at C:\Projects\spsave\node_modules\gulp-mocha\node_modules\mocha\lib\runner.js:315:7
    at done (C:\Projects\spsave\node_modules\gulp-mocha\node_modules\mocha\lib\runnable.js:287:5)
    at C:\Projects\spsave\node_modules\gulp-mocha\node_modules\mocha\lib\runnable.js:360:7
    at C:\Projects\spsave\lib\test\integration\integration.spec.js:45:17
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```
