### ISSUE TITLE
404 NOT FOUND

### ISSUE THREAD

**Issue by mbaertschi** [s-KaiNet/spsave#19]
Hi there

I'm not sure whether this is a bug or just an inability of me. Issuing following cURL request successfully uploads the filename.txt file to the specified folder.

``` bash
curl -v --ntlm --user [username]@[domain].ch:[password] --upload-file fielname.txt
https://sharepoint.[domain].ch/path/to/folder/filename.txt
```

However, if I use spsave with the following settings:

``` javascript
var sp;

sp = require('spsave');

sp.spsave({
        siteUrl: 'https://sharepoint.[domain].ch',
        username: '[username]@[domain].ch',
        password: '[password]',
        folder: "path/to/folder",
        fileName: 'filename.txt',
        fileContent: 'test',
        checkin: true,
        checkinType: 1
    })
    .then(function() {
        console.log('saved');
    })
    .catch(function(err) {
        console.log(err.message);
    }); 
```

then I receive the following error:

``` text
[08:14:13] spsave: Error occured:
[08:14:13] spsave: 404 - "404 NOT FOUND"

[08:14:13] spsave: Stack trace:

[08:14:13] spsave: StatusCodeError: 404 - "404 NOT FOUND"
    at new StatusCodeError (/opt/turntable/node_modules/request-promise/lib/errors.js:32:15)
    at Request.RP$callback [as _callback] (/opt/turntable/node_modules/request-promise/lib/rp.js:77:29)
    at Request.self.callback (/opt/turntable/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/opt/turntable/node_modules/request/request.js:1041:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/opt/turntable/node_modules/request/request.js:968:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
From previous event:
    at FileSaver.checkoutFile (/opt/turntable/node_modules/spsave/lib/src/core/FileSaver.js:166:23)
    at FileSaver.saveFile (/opt/turntable/node_modules/spsave/lib/src/core/FileSaver.js:48:35)
    at FileSaver.save (/opt/turntable/node_modules/spsave/lib/src/core/FileSaver.js:35:18)
    at saveSingleFile (/opt/turntable/node_modules/spsave/lib/src/core/SPSave.js:71:47)
    at /opt/turntable/node_modules/spsave/lib/src/core/SPSave.js:37:13
From previous event:
    at Object.spsave (/opt/turntable/node_modules/spsave/lib/src/core/SPSave.js:13:12)
    at Object.<anonymous> (/path/to/script/sharepoint.js:5:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

The error is thrown while trying to get the GetFileByServerRelativeUrl via GET request.
`https://sharepoint.[domain].ch/_api/web/GetFileByServerRelativeUrl(@FileUrl)?@FileUrl=\'[path/to/folder/filename.txt\'`

Why does spsave wants to get the file by server relative url? I want to upload and not to download the file.

Best,
Michael

**Comment by koltyakov** [comment]
Hi Michael,

Could you try the following:

...
siteUrl: 'https://sharepoint.[domain].ch',
username: '[username]',
password: '[password]',
domain: '[domain]'
...

Best regards,
Andrew

**Comment by s-KaiNet** [comment]
Hi Michael, please try approach suggested above. 
If it doesn't help, make sure you are using latest version of spsave (2.1**3**). 
If nothing helps, please tell me exact latest CU number which is installed on your farm.   

> Why does spsave wants to get the file by server relative url? I want to upload and not to download the file.   

Since you provided `checkin:true`, `spsave` tries to get current checkin status for document by getting metadata for the file.

**Comment by mbaertschi** [comment]
Hi all

Thanks for the fast response.

Adding domain to the settings did not help, but changed the error message. Now I receive:

``` bash
[08:45:09] spsave: Error occured:
[08:45:09] spsave: 401 - undefined

[08:45:09] spsave: Stack trace:

[08:45:09] spsave: StatusCodeError: 401 - undefined
    at new StatusCodeError (/opt/turntable/node_modules/request-promise/lib/errors.js:32:15)
    at Request.RP$callback [as _callback] (/opt/turntable/node_modules/request-promise/lib/rp.js:77:29)
    at Request.self.callback (/opt/turntable/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/opt/turntable/node_modules/request/request.js:1041:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/opt/turntable/node_modules/request/request.js:968:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
From previous event:
    at FileSaver.checkoutFile (/opt/turntable/node_modules/spsave/lib/src/core/FileSaver.js:166:23)
    at FileSaver.saveFile (/opt/turntable/node_modules/spsave/lib/src/core/FileSaver.js:48:35)
    at FileSaver.save (/opt/turntable/node_modules/spsave/lib/src/core/FileSaver.js:35:18)
    at saveSingleFile (/opt/turntable/node_modules/spsave/lib/src/core/SPSave.js:71:47)
    at /opt/turntable/node_modules/spsave/lib/src/core/SPSave.js:37:13
From previous event:
    at Object.spsave (/opt/turntable/node_modules/spsave/lib/src/core/SPSave.js:13:12)
    at Object.<anonymous> (/path/to/script/sharepoint.js:5:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

spsave is at 2.1.3. 

Unfortunately the SharePoint is hosted by my customer and I don't have the CU number right now. I will write him an email.

The checkin feature should work even if the file does not yet exists, right? Could it be a problem that my SharePoint siteUrl is different from the standard siteUrl structure (domain coming after sharepoint)?

Thanks for your information.

Best,
Michael

**Comment by s-KaiNet** [comment]
It looks like your SharePoint uses different authentication scheme. For `spsave` to work, ntlm windows authentication should be enabled. I'm not sure if it works with Kerberos, and it doesn't work with adfs.  
Can you confirm that ntlm is enabled for you web app?

**Comment by s-KaiNet** [comment]
> The checkin feature should work even if the file does not yet exists, right?    

Right

> Could it be a problem that my SharePoint siteUrl is different from the standard siteUrl structure (domain coming after sharepoint)?    

Hm.. I don't think so..

**Comment by s-KaiNet** [comment]
To be sure - you are **not** SharePoint online, you are on-premise, right?

**Comment by mbaertschi** [comment]
> Can you confirm that ntlm is enabled for you web app?

Yes, ntlm is enabled as the cURL request runs successfully

> To be sure - you are note SharePoint online, you are on-premise, right?

I need to get some more information from my client about the SharePoint version. Once I have the information I will try again. Until then we can close the issue if this is ok for you?

**Comment by s-KaiNet** [comment]
yes, absolutely ok
