### ISSUE TITLE
upload file to SharePoint Online failed

### ISSUE THREAD

**Issue by zhijunzhou** [s-KaiNet/spsave#25]
I try to upload file to SharePoint Online, but get the following error message:

```
[13:39:04] Using gulpfile C:\zhou__project_\tss\gulpfile.js
[13:39:04] Starting 'level1'...
[13:39:04] Finished 'level1' after 21 ms
[13:39:04] Starting 'default'...
[13:39:04] Finished 'default' after 63 μs
[13:39:05] spsave: Error occured:
[13:39:05] spsave: Error: socket hang up

[13:39:05] spsave: Stack trace:

[13:39:05] spsave: RequestError: Error: socket hang up
    at new RequestError (C:\zhou__project_\tss\node_modules\request-promise-core
\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\zhou__project_\tss\node_modules\request-pro
mise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\zhou__project_\tss\node_modules\re
quest-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\zhou__project_\tss\node_modules\request\request.js:186:
22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\zhou__project_\tss\node_modules\request\reques
t.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketOnEnd (_http_client.js:344:9)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:973:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
From previous event:
    at coreRequest (C:\zhou__project_\tss\node_modules\sp-request\lib\src\core\S
PRequest.js:15:16)
    at spRequestFunc (C:\zhou__project_\tss\node_modules\sp-request\lib\src\core
\SPRequest.js:56:20)
    at Function.spRequestFunc.(anonymous function) [as get] (C:\zhou__project_\t
ss\node_modules\sp-request\lib\src\core\SPRequest.js:96:24)
    at FileSaver.getFileByUrl (C:\zhou__project_\tss\node_modules\spsave\lib\src
\core\FileSaver.js:210:31)
    at C:\zhou__project_\tss\node_modules\spsave\lib\src\core\FileSaver.js:175:1
9
From previous event:
    at FileSaver.checkoutFile (C:\zhou__project_\tss\node_modules\spsave\lib\src
\core\FileSaver.js:170:23)
    at FileSaver.saveFile (C:\zhou__project_\tss\node_modules\spsave\lib\src\cor
e\FileSaver.js:50:35)
    at FileSaver.save (C:\zhou__project_\tss\node_modules\spsave\lib\src\core\Fi
leSaver.js:37:18)
    at saveSingleFile (C:\zhou__project_\tss\node_modules\spsave\lib\src\core\SP
Save.js:74:76)
    at C:\zhou__project_\tss\node_modules\spsave\lib\src\core\SPSave.js:40:13
From previous event:
    at spsave (C:\zhou__project_\tss\node_modules\spsave\lib\src\core\SPSave.js:
12:12)
    at Gulp.<anonymous> (C:\zhou__project_\tss\gulpfile.js:31:5)
    at module.exports (C:\zhou__project_\tss\node_modules\orchestrator\lib\runTa
sk.js:34:7)
    at Gulp.Orchestrator._runTask (C:\zhou__project_\tss\node_modules\orchestrat
or\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\zhou__project_\tss\node_modules\orchestrat
or\index.js:214:10)
    at Gulp.Orchestrator.start (C:\zhou__project_\tss\node_modules\orchestrator\
index.js:134:8)
    at C:\Users\zhouzh\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^
3.7.0\index.js:46:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
{"name":"RequestError","message":"Error: socket hang up","cause":{"code":"ECONNR
ESET"},"error":{"code":"ECONNRESET"},"options":{"simple":false,"strictSSL":false
,"json":true,"form":{"login":"xxx@xxx.com"},"uri":"https://login.microso
ftonline.com/GetUserRealm.srf","method":"POST","resolveWithFullResponse":false,"
transform2xxOnly":false}}
```

My gulp task:
```
const coreOptions = {
    siteUrl: env.staging,
    notification: true,
    checkin: true,
    checkinType: 1
}

const creds = {
    username: 'xxx@xxx.com' , 
    password: '**********'
}

const fileOptions = {
    folder: 'SiteAssets',
    fileName: 'test.txt',
    fileContent: '0'
}

gulp.task('default', function() {
    spsave(coreOptions, creds, fileOptions)
    .then(function() {
        console.log('uploaded!');
    }).catch(function(err) {
        console.log(JSON.stringify(err));
    });
})
```

Could you help me?

**Comment by koltyakov** [comment]
Hi @zhijunzhou,

In my experience, I received the same `ECONNRESET` code errors because of the network issue in situations with poor internet connection. The symptom is sometimes it works, sometimes not. Maybe this is the case?

Does the same issue appear all the way or occasionally?
Can you try the same on other client machine or even network?
Yet another idea is to check firewall, does it allows node.js process to access the internet.

**Comment by zhijunzhou** [comment]
@koltyakov 

I thinks it's not the network issues because i can upload files to SharePoint 2013 using the same code.
```
C:\zhou__project_\tss>gulp
[13:38:04] Using gulpfile C:\zhou__project_\tss\gulpfile.js
[13:38:04] Starting 'level1'...
[13:38:04] Finished 'level1' after 20 ms
[13:38:04] Starting 'default'...
[13:38:04] Finished 'default' after 50 μs
[13:38:10] spsave: test.txt checked out.
[13:38:13] spsave: test.txt successfully uploaded to 'https://xx.sharepoint.
xxx.com/teams/xxx/SiteAssets' and checked in. Checkin type: majo
r
uploaded!

```
And I think this issue not appear occasionally. You can check the logs i pasted above
```
{"name":"RequestError","message":"Error: socket hang up","cause":{"code":"ECONNR
ESET"},"error":{"code":"ECONNRESET"},"options":{"simple":false,"strictSSL":false
,"json":true,"form":{"login":"xxx@xxx.com"},"uri":"https://login.microso
ftonline.com/GetUserRealm.srf","method":"POST","resolveWithFullResponse":false,"
transform2xxOnly":false}}
```

**Comment by s-KaiNet** [comment]
From your stack trace it doesn't look for me as `spsave` related issue. May be something wrong with your nodejs network connectivity. I've just run tests for SP Online and everything works just fine.      

Check your internet connection, firewall, proxy (you may have proxy configured for OS, but node.js doesn't see that, it requires separate configuration). You are not able to reach `login.microso
ftonline.com`. Try to open it in a browser, try to ping it and see the result.   

PS don't use `0` as content, sometimes that might leads to issues

**Comment by zhijunzhou** [comment]
@s-KaiNet 

You are right, I really have proxy configured for my OS. Is there a way to set up proxy separately?

Meanwhile, if the problem like this persists, then can we consider configuring the proxy in the next release?

Thanks a lot!

**Comment by s-KaiNet** [comment]
Actually I don't have plans to include it, because proxy can be easily configured from outside.   
Take a look at the following issue - [How to configure proxy for spsave](https://github.com/s-KaiNet/gulp-spsave/issues/23)

**Comment by koltyakov** [comment]
@zhijunzhou, 

> I thinks it's not the network issues because i can upload files to SharePoint 2013 using the same code.

This makes me consider that it is a network issue, more.
On-Prem environments are usually close to the client and can be even in the same network with LAN access. It can be easy that node.js process can't access the internet.

> And I think this issue not appear occasionally. You can check the logs i pasted above

Yep, I saw it. `ECONNRESET` - connection abrupted (network latency timeout) when talking to `https://login.microsoftonline.com`.

If it were an authentication issue the message and stack trace would be absolutely different.
If it were the issue inside SPSave or permissions settings error messages would be obvious and connected to the reason closely as it were a REST exception response or 401 error for instance, like:

// Wrong password response
```bash
spsave: <S:Fault>
  <S:Code>
    <S:Value>S:Sender</S:Value>
    <S:Subcode>
      <S:Value>wst:FailedAuthentication</S:Value>
    </S:Subcode>
  </S:Code>
  <S:Reason>
    <S:Text xml:lang="en-US">Authentication Failure</S:Text>
  </S:Reason>
  <S:Detail>
    <psf:error>
      <psf:value>0x80048821</psf:value>
      <psf:internalerror>
        <psf:code>0x80041012</psf:code>
        <psf:text>The entered and stored passwords do not match.</psf:text>
      </psf:internalerror>
    </psf:error>
  </S:Detail>
</S:Fault>
```

// Access denied
```bash
spsave: 403 - "{\"error\":{\"code\":\"-2147024891, System.UnauthorizedAccessException\",\"message\":{\"lang\":\"en-US\",\"value\":\"Access denied. You do not have permission to perform this
action or access this resource.\"}}}"
```

**Comment by koltyakov** [comment]
Uppps, guys, while I was in process of posting last response you managed to come to the conjecture with a proxy.

**Comment by zhijunzhou** [comment]
@s-KaiNet @koltyakov 

Thanks for your help! Please forgive my delay. In the last hour I attended a meeting.

I try to set the proxy and log it in my gulpfile.js, and then I get the following error message:
```
C:\zhou__project_\tss>gulp
https://web-proxy.xxx.com:8080
http://web-proxy.xxx.com:8080
[17:16:36] Using gulpfile C:\zhou__project_\tss\gulpfile.js
[17:16:37] Starting 'level1'...
[17:16:37] Finished 'level1' after 32 ms
[17:16:37] Starting 'default'...
[17:16:37] Finished 'default' after 25 μs
[17:16:39] spsave: Error occured:
[17:16:39] spsave: Cannot read property 'firstChild' of undefined

[17:16:39] spsave: Stack trace:

[17:16:39] spsave: TypeError: Cannot read property 'firstChild' of undefined
    at C:\zhou__project_\tss\node_modules\node-sp-auth\lib\src\utils\AdfsHelper.
js:32:67
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
From previous event:
    at coreRequest (C:\zhou__project_\tss\node_modules\sp-request\lib\src\core\S
PRequest.js:15:16)
    at spRequestFunc (C:\zhou__project_\tss\node_modules\sp-request\lib\src\core
\SPRequest.js:56:20)
    at Function.spRequestFunc.(anonymous function) [as get] (C:\zhou__project_\t
ss\node_modules\sp-request\lib\src\core\SPRequest.js:96:24)
    at FileSaver.getFileByUrl (C:\zhou__project_\tss\node_modules\spsave\lib\src
\core\FileSaver.js:210:31)
    at C:\zhou__project_\tss\node_modules\spsave\lib\src\core\FileSaver.js:175:1
9
From previous event:
    at FileSaver.checkoutFile (C:\zhou__project_\tss\node_modules\spsave\lib\src
\core\FileSaver.js:170:23)
    at FileSaver.saveFile (C:\zhou__project_\tss\node_modules\spsave\lib\src\cor
e\FileSaver.js:50:35)
    at FileSaver.save (C:\zhou__project_\tss\node_modules\spsave\lib\src\core\Fi
leSaver.js:37:18)
    at saveSingleFile (C:\zhou__project_\tss\node_modules\spsave\lib\src\core\SP
Save.js:74:76)
    at C:\zhou__project_\tss\node_modules\spsave\lib\src\core\SPSave.js:40:13
From previous event:
    at spsave (C:\zhou__project_\tss\node_modules\spsave\lib\src\core\SPSave.js:
12:12)
    at Gulp.<anonymous> (C:\zhou__project_\tss\gulpfile.js:48:5)
    at module.exports (C:\zhou__project_\tss\node_modules\orchestrator\lib\runTa
sk.js:34:7)
    at Gulp.Orchestrator._runTask (C:\zhou__project_\tss\node_modules\orchestrat
or\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\zhou__project_\tss\node_modules\orchestrat
or\index.js:214:10)
    at Gulp.Orchestrator.start (C:\zhou__project_\tss\node_modules\orchestrator\
index.js:134:8)
    at C:\Users\zhouzh\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^
3.7.0\index.js:46:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
{}
```

**Comment by s-KaiNet** [comment]
That's not good :)    
Can you please open `node_modules\node-sp-auth\lib\src\utils\AdfsHelper.
js` and put `console.log(xmlResponse)` on line 31 (right after `.then(function (xmlResponse) {`) and post result here (check carefully before posting if xml content doesn't contain sensitive data).

**Comment by zhijunzhou** [comment]
```
[17:46:14] Using gulpfile C:\zhou__project_\tss\gulpfile.js
[17:46:14] Starting 'level1'...
[17:46:14] Finished 'level1' after 27 ms
[17:46:14] Starting 'default'...
[17:46:14] Finished 'default' after 62 μs
<!DOCTYPE html>


<!-- template name: http.error.page.template.html -->


<html lang="en" dir="ltr">
<head>
    <title>http.error.page.template.title</title>
    <base href="https://login.ext.xxx.com/" />
    <meta name="robots" content="noindex, nofollow" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="initial-scale=1.0, minimum-scale=1.0, maximum
-scale=1.0, user-scalable=no" />
    <link rel="stylesheet" type="text/css" href="assets/css/main.css" />
</head>

<body>
<div class="ping-container">
    <div class="ping-header">
        http.error.page.template.title
    </div><!-- .ping-header -->
    <div class="ping-body-container">
        <div class="section-title">
            http.error.page.template.header
        </div>
        <div class="ping-messages ping-nopad">
            <div>
                http.error.page.template.errorMessage
            </div>
            <div class="ping-note-text">
                404 - Not Found
            </div>
        </div>
    </div> <!-- .ping-body-container -->
    <div class="ping-footer-container">
        <div class="ping-footer">
            <div class="ping-credits">
                <a href="http://www.pingidentity.com">PingIdentity</a>
            </div>
        </div> <!-- .ping-footer -->
    </div> <!-- .ping-footer-container -->
</div> <!-- .ping-container -->
</body>
</html>
```

**Comment by s-KaiNet** [comment]
I'm guessing you are using third party SSO provider for Office 365 - ping identity.   
If that's a case I'm afraid there is no way to use username\password for authentication.   
You can go ahead with add-in only authentication as described [here](https://github.com/s-KaiNet/node-sp-auth/wiki/SharePoint%20Online%20addin%20only%20authentication)

**Comment by zhijunzhou** [comment]
@s-KaiNet 

As you say, my company are using third party SSO provider for Office 365. That means I cannot use 'spsave' in my case. 

No matter what, thanks for you help! I will try to use the way you shared to have a further investigate.

Best Regards!

**Comment by s-KaiNet** [comment]
np, feel free to ask further questions, if any
