### ISSUE TITLE
401 - undefined error

### ISSUE THREAD

**Issue by kunalkankariya** [s-KaiNet/spsave#35]
I get the following error when I try to use spsave

> [14:32:20] spsave: Error occured:
[14:32:20] **spsave: 401 - undefined**

[14:32:20] spsave: Stack trace:

[14:32:20] **spsave: StatusCodeError: 401 - undefined**
    at new StatusCodeError (C:\Users\kk\Downloads\KD\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\kk\Downloads\KD\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\kk\Downloads\KD\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\kk\Downloads\KD\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\kk\Downloads\KD\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\kk\Downloads\KD\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

My gulpfile

`    var gulp = require("gulp");
    var spsave = require("gulp-spsave");
    var coreOptions = {
        siteUrl: "xxxxxx",
        folder: "Style Library/js/",
        notification: true
    };
    var creds = {
     username:'xx@xx.com',
        password:'xxx'
    };
    gulp.task("upload", function () {
        return gulp.src("./assets/*.js").pipe(spsave(coreOptions,creds));
    });
`

**_I have also tried using ondemand authentication with the same credentials and I get this error message_** 

> 

**[14:46:08] spsave: Error occured:
[14:46:08] spsave: 403 - {"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}}}**

[14:46:08] spsave: Stack trace:

[14:46:08] spsave: StatusCodeError: 403 - {"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}}}
    at new StatusCodeError (C:\Users\kk\Downloads\KD\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\kk\Downloads\KD\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\kk\Downloads\KD\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\kk\Downloads\KD\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\kk\Downloads\KD\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\kk\Downloads\KD\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by s-KaiNet** [comment]
Hi, a few questions:   
- are you on-premise? I guess yes
- have you tried specifying `domain` option in credentials object?
- which type of authentication do you server have? I bet ntlm V2. Could you please check it? Please check on the registry for the below key value (on the sharepoint server) - [https://technet.microsoft.com/en-us/library/cc960646.aspx](https://technet.microsoft.com/en-us/library/cc960646.aspx)

**Comment by kunalkankariya** [comment]
Apologies for the late reply @s-KaiNet.

I am on SharePoint Online.

I have also tried using app only authentication ( clientId & clientSecret) and I got this error

[16:45:01] spsave: Unable to resolve hosting environment. Site url: https://xyz

[16:45:01] spsave: Stack trace:

[16:45:01] spsave: Error: Unable to resolve hosting environment. Site url: https://xyz
at Function.ResolveHostingEnvironment (C:\Users\kk\Downloads\KD\node_modules\node-sp-auth\lib\src\utils\UrlHelper.js:32:15)
at new OnlineResolver (C:\Users\kk\Downloads\KD\node_modules\node-sp-auth\lib\src\auth\resolvers\base\OnlineResolver.js:8:57)
at new OnlineAddinOnly (C:\Users\kk\Downloads\KD\node_modules\node-sp-auth\lib\src\auth\resolvers\OnlineAddinOnly.js:13:9)
at Function.resolve (C:\Users\kk\Downloads\KD\node_modules\node-sp-auth\lib\src\auth\AuthResolverFactory.js:31:20)
at Object.getAuth (C:\Users\kk\Downloads\KD\node_modules\node-sp-auth\lib\src\index.js:8:54)
at C:\Users\kk\Downloads\KD\node_modules\sp-request\lib\src\core\SPRequest.js:40:20

I did some digging and saw the file node_modules\node-sp-auth\lib\src\utils\UrlHelper.js and it validates the url amongst a list of prededefined domains but the tenant I use doesn't belong to any of those and hence the error I guess.

**Comment by koltyakov** [comment]
Hey @kunalkankariya,

Is `https://xyz` is a real URL you're using or just an abstraction while posting here?  
Are you on O365 Dedicated with a custom domain?
If so, please try updating `node-sp-auth` to the latest one.

**Comment by kunalkankariya** [comment]
It is just an abstraction. I can't reveal the URL here. Yes, custom domain it is. 

I will try updating node-sp-auth and keep you posted.

**Comment by koltyakov** [comment]
So, yep, in this case, please update the dependent library. Details can be found [here](https://github.com/s-KaiNet/node-sp-auth/issues/39).

**Comment by kunalkankariya** [comment]
I had earlier changed the code to return hosting env as Production before you posted the details of the issue above. It timed out. Changed my internet connection to a different network and works now :) 

Thanks :+1:

**Comment by kunalkankariya** [comment]
Wondering why the other authentication methods failed though, MFA could be an issue?

**Comment by koltyakov** [comment]
MFA is an issue, that's true. <-- UPD: Auth with MFA is possible with an [extra setting](https://github.com/s-KaiNet/gulp-spsave/issues/31#issuecomment-360161754)
Also, SAML can't be resolved with O365 Dedicated, as, at the moment, there is no strict criteria for identifying SPO on the custom domains. We're discussing a custom parameter which tells auth lib that it should treat SPO on a custom domain as SPO but not OnPrem.

**Comment by kunalkankariya** [comment]
Thanks @koltyakov and @s-KaiNet . I will close this now.
