### ISSUE TITLE
Getting HTTP 401, SP 2013

### ISSUE THREAD

**Issue by romankua** [s-KaiNet/spsave#40]
Hello!
I was trying to learn some new stuff which is described in this nice article http://julieturner.net/2018/01/conquer-your-dev-toolchain-in-classic-sharepoint-part-2/
But I can't get spsave to work in my environment, I'm getting error 401 =(
Please, can you suggest some ideas how to debug the issue?

Stacktrace:
> spsave: StatusCodeError: 401 - "{\"error\":{\"code\":\"-2147024891, System.UnauthorizedAccessException\",\"message\":{\"lang\":\"uk-UA\",\"value\":\"\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f \\u0437\\u0430\\u0431\\u043e\\u0440\\u043e\\u043d\\u0435\\u043d\\u043e. \\u0423 \\u0432\\u0430\\u0441 \\u043d\\u0435\\u043c\\u0430\\u0454 \\u0434\\u043e\\u0437\\u0432\\u043e\\u043b\\u0456\\u0432 \\u043d\\u0430 \\u0432\\u0438\\u043a\\u043e\\u043d\\u0430\\u043d\\u043d\\u044f \\u0446\\u0456\\u0454\\u0457 \\u0434\\u0456\\u0457 \\u0430\\u0431\\u043e \\u043d\\u0430 \\u0434\\u043e\\u0441\\u0442\\u0443\\u043f\\u0434\\u043e \\u0446\\u044c\\u043e\\u0433\\u043e \\u0440\\u0435\\u0441\\u0443\\u0440\\u0441\\u0443.\"},\"innererror\":{\"message\":\"<nativehr>0x80070005</nativehr><nativestack></nativestack>\\u041d\\u0435\\u043c\\u0430\\u0454 \\u0434\\u043e\\u0441\\u0442\\u0443\\u043f\\u0443.\",\"type\":\"System.UnauthorizedAccessException\",\"stacktrace\":\"   at Microsoft.SharePoint.SPGlobal.HandleUnauthorizedAccessException(UnauthorizedAccessException ex)\\r\\n at Microsoft.SharePoint.Library.SPRequest.PutFile(String bstrUrl, String bstrWebRelativeUrl, Object punkFile, Int64 cbFile, Object punkSPFileMgr, Object punkFFM, Int64 PutFileOpt, String bstrCreatedBy, String bstrModifiedBy, Int32 iCreatedByID, Int32 iModifiedByID, Object varTimeCreated, Object varTimeLastModified, Object varProperties, String bstrCheckinComment, String bstrLockIdMatch, String bstEtagToMatch, Int32 lockType, String lockId, Int32 minutes, Int32 fRefreshLock, Int32 bValidateReqFields, Guid gNewDocId, SPFileSaveParams sfsp, SPFileInfo& pFileProps, UInt32& pdwVirusCheckStatus, String& pVirusCheckMessage, String& pEtagReturn, Byte& piLevel, Int32& pbIgnoredReqProps)\\r\\n   at Microsoft.SharePoint.SPFileCollection.AddStreamOrBytesInternal(String urlOfFile, Stream file, Int64 fileSizeToSave, SPFileStreamManager spmgr, PutFileOpt fileOpt, String createdBy, String modifiedBy, Int32 createdByID, Int32 modifiedByID, DateTime timeCreated, DateTime timeLastModified, Object varProperties, String checkInComment, Stream formatMetadata, String lockIdMatch, String etagToMatch, SPLockType lockType, String lockId, TimeSpan lockTimeout, Boolean validateRequiredFields, SPVirusCheckStatus& virusCheckStatus, String& virusCheckMessage, String& etagNew, Boolean& ignoredRequiredProps)\\r\\n   at Microsoft.SharePoint.SPFileCollection.Add(String urlOfFile, Stream file, Boolean overwrite, String checkInComment, Boolean checkRequiredFields)\\r\\n   at Microsoft.SharePoint.SPFileCollection.Add(SPFileCreationInformation parameters)\\r\\n   at Microsoft.SharePoint.Client.ServerStub.InvokeMethodWithMonitoredScope(Object target, String methodName, ClientValueCollection args, ProxyContext proxyContext, Boolean& isVoid)\\r\\n   at Microsoft.SharePoint.Client.Rest.RestRequestProcessor.InvokeMethod(Boolean mainRequestPath, Object value, ServerStub serverProxy, EdmParserNode node, Boolean resourceEndpoint, MethodInformation methodInfo, Boolean isExtensionMethod, Boolean isIndexerMethod)\\r\\n   at Microsoft.SharePoint.Client.Rest.RestRequestProcessor.GetObjectFromPathMember(Boolean mainRequestPath, String path, Object value, EdmParserNode node, Boolean resourceEndpoint, MethodInformation& methodInfo)\\r\\n   at Microsoft.SharePoint.Client.Rest.RestRequestProcessor.GetObjectFromPath(Boolean mainRequestPath, String path, String pathForErrorMessage)\\r\\n   at Microsoft.SharePoint.Client.Rest.RestRequestProcessor.Process()\\r\\n   at Microsoft.SharePoint.Client.Rest.RestRequestProcessor.ProcessRequest()\\r\\n   at Microsoft.SharePoint.Client.Rest.RestService.ProcessQuery(Stream inputStream, IList`1 pendingDisposableContainer)\"}}}"
>     at new StatusCodeError (/media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/request-promise-core/lib/errors.js:32:15)
>     at Request.plumbing.callback (/media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/request-promise-core/lib/plumbing.js:104:33)
>     at Request.RP$callback [as _callback] (/media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/request-promise-core/lib/plumbing.js:46:31)
>     at Request.self.callback (/media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/request/request.js:185:22)
>     at emitTwo (events.js:126:13)
>     at Request.emit (events.js:214:7)
>     at Request.<anonymous> (/media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/request/request.js:1157:10)
>     at emitOne (events.js:116:13)
>     at Request.emit (events.js:211:7)
>     at IncomingMessage.<anonymous> (/media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/request/request.js:1079:12)
>     at Object.onceWrapper (events.js:313:30)
>     at emitNone (events.js:111:20)
>     at IncomingMessage.emit (events.js:208:7)
>     at endReadableNT (_stream_readable.js:1064:12)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)
> From previous event:
>     at coreRequest (/media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/sp-request/lib/src/core/SPRequest.js:22:16)
>     at spRequestFunc (/media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/sp-request/lib/src/core/SPRequest.js:69:20)
>     at Function.spRequestFunc.(anonymous function) [as post] (/media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/sp-request/lib/src/core/SPRequest.js:109:24)
>     at /media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/spsave/lib/src/core/FileSaver.js:57:36
>     at runCallback (timers.js:794:20)
>     at tryOnImmediate (timers.js:752:5)
>     at processImmediate [as _immediateCallback] (timers.js:729:5)
> From previous event:
>     at FileSaver.saveFile (/media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/spsave/lib/src/core/FileSaver.js:56:14)
>     at FileSaver.save (/media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/spsave/lib/src/core/FileSaver.js:38:18)
>     at saveSingleFile (/media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/spsave/lib/src/core/SPSave.js:80:76)
>     at /media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/spsave/lib/src/core/SPSave.js:41:13
> From previous event:
>     at spsave (/media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/spsave/lib/src/core/SPSave.js:13:12)
>     at /media/user/data/tasks/dev/sp-pnp/demos/test/gulpfile.js:45:25
>     at wrappedMapper (/media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/map-stream/index.js:83:19)
>     at Stream.stream.write (/media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/map-stream/index.js:95:21)
>     at TaskProxy._runProxiedTask (/media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/gulp-cache/lib/index.js:413:8)
>     at TaskProxy._runProxiedTaskAndQueueCache (/media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/gulp-cache/lib/index.js:357:15)
>     at /media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/gulp-cache/lib/index.js:121:10
>     at Generator.next (<anonymous>)
>     at step (/media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
>     at /media/user/data/tasks/dev/sp-pnp/demos/test/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
>     at <anonymous>

My code which does not work:

```
const spsaveOptions = {
    site: {
        siteUrl: settingsShared.siteCollURL, // like "https://server.domain.com"
        checkinType: 2,
        checkin: false
    },
    creds: {
        domain: settingsPrivate.domain, // like "domain"
        username: settingsPrivate.username, // like "username"
        password: settingsPrivate.password // like "password"
    }
};

gulp.task("copyToSharePointFolder",
    function () {
        gulp.src(settingsShared.srcFiles)
            .pipe(
                cache(
                    map(function (file, cb) {
                        console.log(spsaveOptions.creds);
                        spsave(spsaveOptions.site, spsaveOptions.creds, {
                            file: file,
                            folder: settingsShared.destFolder
                        }).then(function () {
                            cb(null, file);
                        }).catch(function () {
                            console.log(arguments);
                        });
                    }),
                    { key: makeHashKey }
                )
            );
    }
);
```

Also I tried this code and it works:

```
var spauth = require('node-sp-auth');
var reqpromise = require('request-promise');

gulp.task("sptest", function () {
    spauth
        .getAuth(spsaveOptions.site.siteUrl, {
            username: spsaveOptions.creds.username,
            password: spsaveOptions.creds.password,
            domain: spsaveOptions.creds.domain
        })
        .then(data => {
            let headers = data.headers;
            headers['Accept'] = 'application/json;odata=verbose';
            let requestOpts = data.options;
            requestOpts.json = true;
            requestOpts.headers = headers;
            requestOpts.url = spsaveOptions.site.siteUrl + '/_api/web';

            reqpromise.get(requestOpts).then(response => {
                console.log(response.d);
            });
        });
});
```
So what could be possible wrong with the first piece of code?

Thank you!

**Comment by romankua** [comment]
PS: Just to clarify. I was able to create files in destination site using browser, so user permissions are not the reason. It's something with my code.

**Comment by romankua** [comment]
I'm really sorry about confusing you. There is some issue with user permissions. Something strange though, ACL is ok, user is able to create folders, but can't upload files. I should have checked it earlier!
Sorry!

**Comment by romankua** [comment]
The reason was that user must have at least Design access level to upload/update files to/in "/Style Library" . It seems this library is special!
