### ISSUE TITLE
will it work through vpn

### ISSUE THREAD

**Issue by simkessy** [s-KaiNet/spsave#41]
I'm working at a client that is using a vpn to connect to SP. I'm current offsite trying to push using SPSave and getting an error: 

```
[14:34:52] Starting 'push'...
[14:34:54] spsave: Error occured:
[14:34:54] spsave: 401 - undefined

[14:34:54] spsave: Stack trace:

[14:34:54] spsave: StatusCodeError: 401 - undefined
    at new StatusCodeError (C:\Users\me\Downloads\x\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\me\Downloads\x\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\me\Downloads\x\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\me\Downloads\x\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\me\Downloads\x\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\me\Downloads\x\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at coreRequest (C:\Users\me\Downloads\x\node_modules\sp-request\lib\src\core\SPRequest.js:22:16)
    at spRequestFunc (C:\Users\me\Downloads\x\node_modules\sp-request\lib\src\core\SPRequest.js:69:20)
    at Function.spRequestFunc.(anonymous function) [as post] (C:\Users\me\Downloads\x\node_modules\sp-request\lib\src\core\SPRequest.js:109:24)
    at C:\Users\me\Downloads\x\node_modules\sp-request\lib\src\core\SPRequest.js:87:27
From previous event:
    at Function.spRequestFunc.requestDigest (C:\Users\me\Downloads\x\node_modules\sp-request\lib\src\core\SPRequest.js:79:16)
    at C:\Users\me\Downloads\x\node_modules\spsave\lib\src\core\FileSaver.js:54:36
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at FileSaver.saveFile (C:\Users\me\Downloads\x\node_modules\spsave\lib\src\core\FileSaver.js:53:14)
    at FileSaver.save (C:\Users\me\Downloads\x\node_modules\spsave\lib\src\core\FileSaver.js:38:18)
    at saveSingleFile (C:\Users\me\Downloads\x\node_modules\spsave\lib\src\core\SPSave.js:80:76)
    at C:\Users\me\Downloads\x\node_modules\spsave\lib\src\core\SPSave.js:41:13
From previous event:
    at spsave (C:\Users\me\Downloads\x\node_modules\spsave\lib\src\core\SPSave.js:13:12)
    at DestroyableTransform.uploadFile [as _transform] (C:\Users\me\Downloads\x\node_modules\gulp-spsave\index.js:42:7)
    at DestroyableTransform.Transform._read (C:\Users\me\Downloads\x\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (C:\Users\me\Downloads\x\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (C:\Users\me\Downloads\x\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_writable.js:313:64)
    at writeOrBuffer (C:\Users\me\Downloads\x\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (C:\Users\me\Downloads\x\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_writable.js:241:11)
    at write (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at emitNone (events.js:106:13)
    at DestroyableTransform.emit (events.js:208:7)
    at emitReadable_ (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:448:10)
    at emitReadable (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:444:5)
    at readableAddChunk (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:145:32)
    at afterTransform (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:101:12)
    at TransformState.afterTransform (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\through2\through2.js:26:3)
    at DestroyableTransform.Transform._read (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:194:11)
[14:34:54] 'push' errored after 2.05 s
[14:34:54] StatusCodeError in plugin "gulp-spsave"
Message:
    401 - undefined
Details:
    statusCode: 401
    error: undefined
    options: [object Object]
    response: [object Object]

Stack:
StatusCodeError: 401 - undefined
    at new StatusCodeError (C:\Users\me\Downloads\x\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\me\Downloads\x\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\me\Downloads\x\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\me\Downloads\x\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\me\Downloads\x\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\me\Downloads\x\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at coreRequest (C:\Users\me\Downloads\x\node_modules\sp-request\lib\src\core\SPRequest.js:22:16)
    at spRequestFunc (C:\Users\me\Downloads\x\node_modules\sp-request\lib\src\core\SPRequest.js:69:20)
    at Function.spRequestFunc.(anonymous function) [as post] (C:\Users\me\Downloads\x\node_modules\sp-request\lib\src\core\SPRequest.js:109:24)
    at C:\Users\me\Downloads\x\node_modules\sp-request\lib\src\core\SPRequest.js:87:27
From previous event:
    at Function.spRequestFunc.requestDigest (C:\Users\me\Downloads\x\node_modules\sp-request\lib\src\core\SPRequest.js:79:16)
    at C:\Users\me\Downloads\x\node_modules\spsave\lib\src\core\FileSaver.js:54:36
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at FileSaver.saveFile (C:\Users\me\Downloads\x\node_modules\spsave\lib\src\core\FileSaver.js:53:14)
    at FileSaver.save (C:\Users\me\Downloads\x\node_modules\spsave\lib\src\core\FileSaver.js:38:18)
    at saveSingleFile (C:\Users\me\Downloads\x\node_modules\spsave\lib\src\core\SPSave.js:80:76)
    at C:\Users\me\Downloads\x\node_modules\spsave\lib\src\core\SPSave.js:41:13
From previous event:
    at spsave (C:\Users\me\Downloads\x\node_modules\spsave\lib\src\core\SPSave.js:13:12)
    at DestroyableTransform.uploadFile [as _transform] (C:\Users\me\Downloads\x\node_modules\gulp-spsave\index.js:42:7)
    at DestroyableTransform.Transform._read (C:\Users\me\Downloads\x\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (C:\Users\me\Downloads\x\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (C:\Users\me\Downloads\x\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_writable.js:313:64)
    at writeOrBuffer (C:\Users\me\Downloads\x\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (C:\Users\me\Downloads\x\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_writable.js:241:11)
    at write (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at emitNone (events.js:106:13)
    at DestroyableTransform.emit (events.js:208:7)
    at emitReadable_ (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:448:10)
    at emitReadable (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:444:5)
    at readableAddChunk (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:145:32)
    at afterTransform (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:101:12)
    at TransformState.afterTransform (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\through2\through2.js:26:3)
    at DestroyableTransform.Transform._read (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (C:\Users\me\Downloads\x\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:194:11)
```

**Comment by s-KaiNet** [comment]
Sorry for late reply...    
Basically it should work with vpn. Based on your error it looks like NTLM V2 issue. NTLM v2 is supported in latest `node-sp-auth` module. So please make sure that you use it.     
Feel free to reopen in case of any questions or issues.
