### ISSUE TITLE
spsave: Error: connect ETIMEDOUT 40.126.1.166:443

### ISSUE THREAD

**Issue by Daneshwaran** [s-KaiNet/spsave#44]
Hi im trying to use spsave package but I facing this issue Error: connect ETIMEDOUT which unable to resolve.
My environment details:
OS: Windows 7
code editor: VS Code
installed spsave by npm
I tried to delete auth data file but it didn't help.
I am using corporate internet with proxy configuration and I have set the same proxy to my npm.

C:\Users\A674684\Documents\Workspace>gulp
[19:14:32] Using gulpfile ~\Documents\Workspace\gulpfile.js
[19:14:32] Starting 'watch'...
[19:14:32] Finished 'watch' after 6.61 ms
[19:14:32] Starting 'default'...
[19:14:32] Starting 'js'...
[19:14:32] Starting 'css'...
[19:14:32] Finished 'default' after 23 ms
[node-sp-auth]: reading auth data from C:\Users\A674684\AppData\Roaming\spauth\creds\https___nokia.sharepoint.com_sites_dannytest.json
[19:14:54] spsave: Error occured:
[19:14:54] spsave: Error: connect ETIMEDOUT 40.126.1.166:443

[19:14:54] spsave: Stack trace:

[19:14:54] spsave: RequestError: Error: connect ETIMEDOUT 40.126.1.166:443
    at new RequestError (C:\Users\A674684\Documents\Workspace\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\A674684\Documents\Workspace\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\A674684\Documents\Workspace\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\A674684\Documents\Workspace\node_modules\request\request.js:185:22)
    at Request.emit (events.js:160:13)
    at Request.onRequestError (C:\Users\A674684\Documents\Workspace\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:160:13)
    at TLSSocket.socketErrorListener (_http_client.js:389:9)
    at TLSSocket.emit (events.js:160:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)
From previous event:
    at coreRequest (C:\Users\A674684\Documents\Workspace\node_modules\sp-request\lib\src\core\SPRequest.js:22:16)
    at spRequestFunc (C:\Users\A674684\Documents\Workspace\node_modules\sp-request\lib\src\core\SPRequest.js:69:20)
    at Function.spRequestFunc.(anonymous function) [as get] (C:\Users\A674684\Documents\Workspace\node_modules\sp-request\lib\src\core\SPRequest.js:109:24)
    at FileSaver.getFileByUrl (C:\Users\A674684\Documents\Workspace\node_modules\spsave\lib\src\core\FileSaver.js:211:31)
    at C:\Users\A674684\Documents\Workspace\node_modules\spsave\lib\src\core\FileSaver.js:176:19
From previous event:
    at FileSaver.checkoutFile (C:\Users\A674684\Documents\Workspace\node_modules\spsave\lib\src\core\FileSaver.js:171:23)
    at FileSaver.saveFile (C:\Users\A674684\Documents\Workspace\node_modules\spsave\lib\src\core\FileSaver.js:51:35)
    at FileSaver.save (C:\Users\A674684\Documents\Workspace\node_modules\spsave\lib\src\core\FileSaver.js:38:18)
    at saveSingleFile (C:\Users\A674684\Documents\Workspace\node_modules\spsave\lib\src\core\SPSave.js:80:76)
    at C:\Users\A674684\Documents\Workspace\node_modules\spsave\lib\src\core\SPSave.js:41:13
From previous event:
    at spsave (C:\Users\A674684\Documents\Workspace\node_modules\spsave\lib\src\core\SPSave.js:13:12)
    at DestroyableTransform.uploadFile [as _transform] (C:\Users\A674684\Documents\Workspace\node_modules\gulp-spsave\index.js:43:7)
    at DestroyableTransform.Transform._read (C:\Users\A674684\Documents\Workspace\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (C:\Users\A674684\Documents\Workspace\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (C:\Users\A674684\Documents\Workspace\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_writable.js:313:64)
    at writeOrBuffer (C:\Users\A674684\Documents\Workspace\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (C:\Users\A674684\Documents\Workspace\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_writable.js:241:11)
    at DestroyableTransform.ondata (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:160:13)
    at addChunk (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at DestroyableTransform._transform (C:\Users\A674684\Documents\Workspace\node_modules\gulp-cached\index.js:43:10)
    at DestroyableTransform.Transform._read (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at write (C:\Users\A674684\Documents\Workspace\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (C:\Users\A674684\Documents\Workspace\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (C:\Users\A674684\Documents\Workspace\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:160:13)
    at emitReadable_ (C:\Users\A674684\Documents\Workspace\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:448:10)
    at emitReadable (C:\Users\A674684\Documents\Workspace\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:444:5)
Unhandled rejection RequestError in plugin 'gulp-spsave'

**Comment by s-KaiNet** [comment]
Have you set up your proxy in nodejs according to [this suggestion](https://github.com/s-KaiNet/gulp-spsave/issues/23#issuecomment-278863914)?

**Comment by Daneshwaran** [comment]
Hello,
Below are the action steps I used to configure proxy for node as per your above suggestion.

set https_proxy=http://[proxy]:[port] 
set http_proxy=http://[proxy]:[port]
set NODE_TLS_REJECT_UNAUTHORIZED=0

Also tried with username and password format "http://" + user + ":" + password + "@" + host + ":" + port; for the above.

using console.log(process.env.http(s)_proxy) I checked the proxy config it was correct.

I got new error after this, below are the stack trace for the same.

[19:23:40] Using gulpfile ~\Documents\Workspace\gulpfile.js
[19:23:40] Starting 'watch'...
[19:23:40] Finished 'watch' after 6.18 ms
[19:23:40] Starting 'default'...
[19:23:40] Starting 'js'...
[19:23:40] Starting 'css'...
[19:23:40] Finished 'default' after 21 ms
[node-sp-auth]: reading auth data from C:\Users\A674684\AppData\Roaming\spauth\creds\https___nokia.sharepoint.com_sites_dannytest.json
[19:23:42] spsave: Error occured:
[19:23:42] spsave: Error: tunneling socket could not be established, statusCode=407

[19:23:42] spsave: Stack trace:

[19:23:42] spsave: RequestError: Error: tunneling socket could not be established, statusCode=407
    at new RequestError (C:\Users\A674684\Documents\Workspace\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\A674684\Documents\Workspace\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\A674684\Documents\Workspace\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\A674684\Documents\Workspace\node_modules\request\request.js:185:22)
    at Request.emit (events.js:160:13)
    at Request.onRequestError (C:\Users\A674684\Documents\Workspace\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:160:13)
    at ClientRequest.onConnect (C:\Users\A674684\Documents\Workspace\node_modules\tunnel-agent\index.js:168:23)
    at Object.onceWrapper (events.js:255:19)
    at ClientRequest.emit (events.js:160:13)
    at Socket.socketOnData (_http_client.js:470:11)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:602:20)
From previous event:
    at coreRequest (C:\Users\A674684\Documents\Workspace\node_modules\sp-request\lib\src\core\SPRequest.js:22:16)
    at spRequestFunc (C:\Users\A674684\Documents\Workspace\node_modules\sp-request\lib\src\core\SPRequest.js:69:20)
    at Function.spRequestFunc.(anonymous function) [as get] (C:\Users\A674684\Documents\Workspace\node_modules\sp-request\lib\src\core\SPRequest.js:109:24)
    at FileSaver.getFileByUrl (C:\Users\A674684\Documents\Workspace\node_modules\spsave\lib\src\core\FileSaver.js:211:31)
    at C:\Users\A674684\Documents\Workspace\node_modules\spsave\lib\src\core\FileSaver.js:176:19
From previous event:
    at FileSaver.checkoutFile (C:\Users\A674684\Documents\Workspace\node_modules\spsave\lib\src\core\FileSaver.js:171:23)
    at FileSaver.saveFile (C:\Users\A674684\Documents\Workspace\node_modules\spsave\lib\src\core\FileSaver.js:51:35)
    at FileSaver.save (C:\Users\A674684\Documents\Workspace\node_modules\spsave\lib\src\core\FileSaver.js:38:18)
    at saveSingleFile (C:\Users\A674684\Documents\Workspace\node_modules\spsave\lib\src\core\SPSave.js:80:76)
    at C:\Users\A674684\Documents\Workspace\node_modules\spsave\lib\src\core\SPSave.js:41:13
From previous event:
    at spsave (C:\Users\A674684\Documents\Workspace\node_modules\spsave\lib\src\core\SPSave.js:13:12)
    at DestroyableTransform.uploadFile [as _transform] (C:\Users\A674684\Documents\Workspace\node_modules\gulp-spsave\index.js:43:7)
    at DestroyableTransform.Transform._read (C:\Users\A674684\Documents\Workspace\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (C:\Users\A674684\Documents\Workspace\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (C:\Users\A674684\Documents\Workspace\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_writable.js:313:64)
    at writeOrBuffer (C:\Users\A674684\Documents\Workspace\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (C:\Users\A674684\Documents\Workspace\node_modules\gulp-spsave\node_modules\readable-stream\lib\_stream_writable.js:241:11)
    at DestroyableTransform.ondata (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:160:13)
    at addChunk (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at DestroyableTransform._transform (C:\Users\A674684\Documents\Workspace\node_modules\gulp-cached\index.js:43:10)
    at DestroyableTransform.Transform._read (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (C:\Users\A674684\Documents\Workspace\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at write (C:\Users\A674684\Documents\Workspace\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (C:\Users\A674684\Documents\Workspace\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (C:\Users\A674684\Documents\Workspace\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:160:13)
    at emitReadable_ (C:\Users\A674684\Documents\Workspace\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:448:10)
    at emitReadable (C:\Users\A674684\Documents\Workspace\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:444:5)
Unhandled rejection RequestError in plugin 'gulp-spsave'

**Comment by s-KaiNet** [comment]
Basically, it should just work, however it seems something wrong happened. Unfortunately, I can't diagnose what's wrong with your proxy setup.     

407 means proxy authentication issue, please check once again that user \ password is correct. Try to URL encode your password.   
Your proxy also should be https proxy, check that as well. I'm not sure if it's required, but just a suggestion.

**Comment by Daneshwaran** [comment]
thank you for your quick reply, I will try it out.
