### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Perneel** [s-KaiNet/spsave#45]
I'm receiving the error below. Just to double check, is this caused because of the 'No files were found' message? Can this be safely ignored?

`{ message: 'No files were uploaded. No files were found which match your criteria.' }
TypeError: Cannot read property 'replace' of undefined
    at Function.UrlHelper.removeTrailingSlash (C:\Users\stbrunee\gitroot\SPDICT-ERGOPORT\sharepoint\node_modules\spsave\lib\src\utils\UrlHelper.js:7:20)
    at new FileSaver (C:\Users\stbrunee\gitroot\SPDICT-ERGOPORT\sharepoint\node_modules\spsave\lib\src\core\FileSaver.js:22:58)
    at saveSingleFile (C:\Users\stbrunee\gitroot\SPDICT-ERGOPORT\sharepoint\node_modules\spsave\lib\src\core\SPSave.js:80:12)
    at saveFileArray (C:\Users\stbrunee\gitroot\SPDICT-ERGOPORT\sharepoint\node_modules\spsave\lib\src\core\SPSave.js:64:9)
    at C:\Users\stbrunee\gitroot\SPDICT-ERGOPORT\sharepoint\node_modules\spsave\lib\src\core\SPSave.js:30:13
    at spsave (C:\Users\stbrunee\gitroot\SPDICT-ERGOPORT\sharepoint\node_modules\spsave\lib\src\core\SPSave.js:13:12)
    at distribute (C:\Users\stbrunee\gitroot\SPDICT-ERGOPORT\sharepoint\webpack.config.js:315:5)
    at Timeout.setTimeout [as _onTimeout] (C:\Users\stbrunee\gitroot\SPDICT-ERGOPORT\sharepoint\webpack.config.js:153:50)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)`

**Comment by s-KaiNet** [comment]
It looks like url was not provided. Do you have sample code on how do you use spsave?

**Comment by Perneel** [comment]
I knew it was gonna be something silly. You were right, issue with the url. Sorry to waste your time...
Thanks for the fast response!

**Comment by s-KaiNet** [comment]
no problem!
