### ISSUE TITLE
 No XML to parse!

### ISSUE THREAD

**Issue by ergomesh** [s-KaiNet/spsave#46]
I have gotten this working on my sharepoint but moving it to a client space i am getting this error  **No XML to parse!**
```
node_modules/node-sp-auth/lib/src/utils/AdfsHelper.js:32:23)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
```

I added some debugging to AdsfHelper.js and am getting no response from the following request **404 File Not Found**

POST https://login.live.com/adfs/services/trust/13/usernamemixed

```<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
    <s:Header>
      <a:Action s:mustUnderstand="1">http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue</a:Action>
      <a:ReplyTo>
        <a:Address>http://www.w3.org/2005/08/addressing/anonymous</a:Address>
      </a:ReplyTo>
      <a:To s:mustUnderstand="1">https://login.live.com/adfs/services/trust/13/usernamemixed</a:To>
      <o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
        <o:UsernameToken u:Id="uuid-ommimtted-token">
          <o:Username>myusername@outlook.com</o:Username>
          <o:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">mypassword</o:Password>
        </o:UsernameToken>
      </o:Security>
    </s:Header>
    <s:Body>
      <trust:RequestSecurityToken xmlns:trust="http://docs.oasis-open.org/ws-sx/ws-trust/200512">
        <wsp:AppliesTo xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
          <wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing">
            <wsa:Address>urn:federation:MicrosoftOnline</wsa:Address>
          </wsa:EndpointReference>
        </wsp:AppliesTo>
        <trust:KeyType>http://docs.oasis-open.org/ws-sx/ws-trust/200512/Bearer</trust:KeyType>
        <trust:RequestType>http://docs.oasis-open.org/ws-sx/ws-trust/200512/Issue</trust:RequestType>
      </trust:RequestSecurityToken>
    </s:Body>
  </s:Envelope>```

**Comment by s-KaiNet** [comment]
How do you provide credentials for `spsave`? Do you use username and password? Do you have MFA enabled for your tenant?

**Comment by ergomesh** [comment]
yes i was using username and password. I do not have control over the site so i will rely the MFA tentant question to the share point admin

**Comment by koltyakov** [comment]
@ergomesh are you also sure that on customers tenant ADFS is used but not some other auth strategy?

**Comment by ergomesh** [comment]
This is the reply I received from their admin "There is not MFA enabled and we use ADFS for internal, but these external account shouldn’t run through that."

Is the only option then to run this using the addin only authentication?

**Comment by s-KaiNet** [comment]
Yes, it looks like in that case addin only auth is the way to go. ADFS auth works for common scenarios, I tested it with my ADFS + SharePoint Online setup. However, sometimes clients have customized ADFS setup and it's really difficult to diagnose the real problem with authentication from nodejs.
