### ISSUE TITLE
Error while resolving authentication class

### ISSUE THREAD

**Issue by pavani003** [s-KaiNet/spsave#55]
I am getting this error while using SharePoint Online addin only authentication with client id and secret.Where exactly should I pass token i get from spauth. I get this error when I pass headers in coreoptions

**Comment by s-KaiNet** [comment]
You shouldn't provide any headers from node-sp-auth.    
Here the bare minimum sample usage:
```javascript
var spsave = require("spsave").spsave;

spsave({
	siteUrl: "https://<org>.sharepoint.com/sites/dev"
}, {
	clientId: "<id>",
	clientSecret: "<secret>"
}, {
	folder: "SiteAssets",
	fileName: "123.txt",
	fileContent: "my text"
})
.then(function(){
	console.log("saved");
})
.catch(function(err){
	console.log(err);
});
```

**Comment by pavani003** [comment]
Now I get this error

403 - undefined
    at new StatusCodeError (C:\Users\guttikop\Documents\learn\Pastebinangular\pastebin\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\guttikop\Documents\learn\Pastebinangular\pastebin\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\guttikop\Documents\learn\Pastebinangular\pastebin\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\guttikop\Documents\learn\Pastebinangular\pastebin\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\Users\guttikop\Documents\learn\Pastebinangular\pastebin\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\Users\guttikop\Documents\learn\Pastebinangular\pastebin\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1085:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
However I am able to upload files using credentials.

**Comment by s-KaiNet** [comment]
Most likely you haven't provided correct permissions for your client app. Please follow steps from [wiki](https://github.com/s-KaiNet/node-sp-auth/wiki/SharePoint-Online-addin-only-authentication) to find out how to do that.
