### ISSUE TITLE
spsave: 429 TOO MANY REQUESTS

### ISSUE THREAD

**Issue by Tiago-Altus** [s-KaiNet/spsave#66]
I am migrating tens of thousands of folders from a local drive to SharePoint. I am using spave to copy files and folders over to SharePoint. At random times I get the 429 error for too many requests. Is there any buffer I should add between spsave calls to prevent this issue?

[23:11:13] spsave: HTTPError: Response code 429 (Too Many Requests)
    at EventEmitter.<anonymous> (C:\Users\...\node_modules\got\dist\source\as-promise.js:118:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
HTTPError: Response code 429 (Too Many Requests)
    at EventEmitter.<anonymous> (C:\Users\...\node_modules\got\dist\source\as-promise.js:118:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by s-KaiNet** [comment]
That's a common SharePoint problem called throttling. You can read more [here](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online).     

You can try to analyze Retry-After header and implement a retry strategy. Alternatively, if you're migrating a lot of files, maybe it's easier to map a SharePoint folder to your local drive and sync automatically?

**Comment by koltyakov** [comment]
For a mass data migration scenario, maybe this helps https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool

**Comment by s-KaiNet** [comment]
Yea, spsave is not the best tool to perform such bulk operations.
