### ISSUE TITLE
Publish to SharePoint from Github using Actions.yml

### ISSUE THREAD

**Issue by jairamjidgekar** [s-KaiNet/spsave#77]
Hi, 

I am trying to upload the files from GitHub to SharePoint. 

I have few steps/actions in the .yml file (basically execution of python scripts and data scraping). 

Once these actions are completed, I create a copy of the files from GitHub to SharePoint. 

When the action is executed, I am getting the below error: 

`[21:57:17] spsave: Error occured:
[21:57:17] spsave: 403 - undefined

[21:57:17] spsave: Stack trace:

[21:57:17] spsave: StatusCodeError: 403 - undefined
    at new StatusCodeError (/app/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/app/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/app/node_modules/request/request.js:11[54](https://github.com/jairamjidgekar/KDB/actions/runs/4791432078/jobs/8521840196#step:11:55):10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:[63](https://github.com/jairamjidgekar/KDB/actions/runs/4791432078/jobs/8521840196#step:11:64):19)`

Here's the code snippet of .yml file:

` with:
              site_url: 'https://****************************/_Enabler/'
              library_folder: 'Shared documents/GitHub_Repo'
              sharepoint_client_id: ${{ secrets.SP_CLIENT_ID }}
              sharepoint_client_secret: ${{ secrets.SP_CLIENT_SECRET }}`

Can you please help me here? What might be the issue for the above failure?

Is it something to do with the Client ID and secret key?

**Comment by hyper-ant** [comment]
I have the same issue. The ID and secret are definitely correct.
