### ISSUE TITLE
Cannot Upload Files

### ISSUE THREAD

**Issue by GurudeepSNaik** [s-KaiNet/spsave#81]
var coreOptions = {
      siteUrl:"https://[domain].sharepoint.com/sites/[folder]",
      notification: true,
      checkin: true,
      checkinType: 1,
    };
    var creds = {
      username: "[user]@[domain].com",
      password: [password],
    };

    var fileOptions = {
      folder: "[folder name]",
      fileName: "file.txt",
      fileContent: "hello world",
    };
 spsave(coreOptions, creds, fileOptions)
      .then(function (data) {
        console.log("File uploaded!", data);
      }).catch(function (err) {
        console.log(err);
      });

TypeError: Cannot read properties of undefined (reading 'firstChild')
    at OnlineUserCredentials.postToken (C:\Server\node_modules\node-sp-auth\lib\src\auth\resolvers\OnlineUserCredentials.js:150:91)
    at C:\Server\node_modules\node-sp-auth\lib\src\auth\resolvers\OnlineUserCredentials.js:48:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[12:51:05] spsave: Error occured:
[12:51:05] spsave: Cannot read properties of undefined (reading 'body')

[12:51:05] spsave: Stack trace:

[12:51:05] spsave: TypeError: Cannot read properties of undefined (reading 'body')
    at C:\Server\node_modules\spsave\lib\src\core\FileSaver.js:200:34
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by koltyakov** [comment]
@GurudeepSNaik seems your configuration could be incorrect.

```javascript
var coreOptions = {
  siteUrl:"https://[domain].sharepoint.com/sites/[folder]", // <--- this part
  notification: true,
  checkin: true,
  checkinType: 1,
};
```

`siteUrl` must be site URL, not a folder.

**Comment by GurudeepSNaik** [comment]
@koltyakov 

`  var coreOptions = {
    siteUrl: "https://[domain].sharepoint.com/sites/DigitalRepository/",
    notification: true,
    checkin: true,
    checkinType: 1,
  };
  var creds = {
    username: [username],
    password: [pass],
  };

  var fileOptions = {
    folder: "NetSuite_Attachments/TEST",
    fileName: "file.txt",
    fileContent: "hello world",
  };

  spsave(coreOptions, creds, fileOptions)
    .then(function (data) {
      console.log("File uploaded!", data);
    })
    .catch(function (err) {
      console.log("File upload failed!", err);
    });`
    
    
    as you mentioned i have added my site url but it gives the same error again i am not sure what i am doing wrong and i have full user access also for that site.
    
    TypeError: Cannot read properties of undefined (reading 'firstChild')
    at OnlineUserCredentials.postToken (C:\Users\Gurudeep\OneDrive\Desktop\Kyra\NCRR\_Server\node_modules\node-sp-auth\lib\src\auth\resolvers\OnlineUserCredentials.js:150:91)
    at C:\Users\Gurudeep\OneDrive\Desktop\Kyra\NCRR\_Server\node_modules\node-sp-auth\lib\src\auth\resolvers\OnlineUserCredentials.js:48:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
